name: OpenWrt for Redmi AC2100

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update apt package lists and install Python 3.5
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y python3.5

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHON: python3.5
        run: |
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib

      - name: Download OpenWrt for Redmi AC2100
        run: |
          git clone https://github.com/Axe-l/myopenwrt.git
          cp .config ./myopenwrt/.config
          mv ./myopenwrt/* ./

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom configure file
        run: |
          make defconfig

      # Add your custom software installation steps here

      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name : Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: bin/targets/
